export const mockKPIs = {
  liquidez: { valor: 1.42, delta: 0.12, positivo: true },
  dso: { valor: 38, delta: 3, positivo: false, sector: 30 },
  burnRate: { valor: 43800, delta: 3.1, positivo: false },
  margenNeto: { valor: 38.4, delta: 2.1, positivo: true },
}

export const mockEvolucion = [
  { mes: 'Ene', ingresos: 72000, gastos: 38000 },
  { mes: 'Feb', ingresos: 78000, gastos: 40000 },
  { mes: 'Mar', ingresos: 82000, gastos: 41000 },
  { mes: 'Abr', ingresos: 94200, gastos: 43800 },
  { mes: 'May', ingresos: 88000, gastos: 42000 },
  { mes: 'Jun', ingresos: 96000, gastos: 44000 },
  { mes: 'Jul', ingresos: 90000, gastos: 43000 },
  { mes: 'Ago', ingresos: 98000, gastos: 45000 },
  { mes: 'Sep', ingresos: 92000, gastos: 43500 },
  { mes: 'Oct', ingresos: 102000, gastos: 46000 },
  { mes: 'Nov', ingresos: 106000, gastos: 47000 },
  { mes: 'Dic', ingresos: 110000, gastos: 48000 },
]

export const puntoEquilibrio = 76500

export const mockPrevisiones = [
  {
    id: 1,
    concepto: 'IVA Q2 · Mod. 303',
    detalle: 'AEAT · Autoliquidación trimestral',
    vencimiento: '2026-04-20',
    categoria: 'Fiscal',
    periodicidad: 'Trimestral',
    importe: 21850,
    estado: 'Pendiente',
    diasRestantes: 11,
    urgente: true,
  },
  {
    id: 2,
    concepto: 'IRPF · Mod. 111',
    detalle: 'AEAT · Retenciones trabajadores',
    vencimiento: '2026-04-20',
    categoria: 'Fiscal',
    periodicidad: 'Trimestral',
    importe: 4200,
    estado: 'Pendiente',
    diasRestantes: 11,
    urgente: true,
  },
  {
    id: 3,
    concepto: 'Nóminas · Mayo 2026',
    detalle: '8 empleados · Seguridad Social incluida',
    vencimiento: '2026-04-30',
    categoria: 'Gasto fijo',
    periodicidad: 'Mensual',
    importe: 18400,
    estado: 'Programado',
    diasRestantes: 21,
    urgente: false,
  },
  {
    id: 4,
    concepto: 'Alquiler oficina',
    detalle: 'Proveedor · Contrato anual',
    vencimiento: '2026-05-01',
    categoria: 'Gasto fijo',
    periodicidad: 'Mensual',
    importe: 2100,
    estado: 'Programado',
    diasRestantes: 22,
    urgente: false,
  },
  {
    id: 5,
    concepto: 'Adobe Creative Cloud',
    detalle: 'Suscripción · 5 licencias',
    vencimiento: '2026-05-05',
    categoria: 'Suscripción',
    periodicidad: 'Mensual',
    importe: 290,
    estado: 'Programado',
    diasRestantes: 26,
    urgente: false,
  },
  {
    id: 6,
    concepto: 'HubSpot CRM',
    detalle: 'Suscripción · Plan Pro',
    vencimiento: '2026-05-10',
    categoria: 'Suscripción',
    periodicidad: 'Mensual',
    importe: 450,
    estado: 'Programado',
    diasRestantes: 31,
    urgente: false,
  },
  {
    id: 7,
    concepto: 'IS Pago fraccionado · Mod. 202',
    detalle: 'AEAT · Impuesto de Sociedades',
    vencimiento: '2026-07-20',
    categoria: 'Fiscal',
    periodicidad: 'Anual',
    importe: 8200,
    estado: 'Estimado',
    diasRestantes: 83,
    urgente: false,
  },
]
